# Generated by Django 4.2.7 on 2024-07-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_alter_user_information_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_information',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
